import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import Button from "../components/button";
import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar";
import Card from "../components/card";
import { MdOutlineCheckBox } from "react-icons/md";
import { useContext } from "react";
import { FirebaseContext } from "../firebase/FirebaseContext";

export default function Home() {
	const lists = [
		"Post your questions",
		"Answer practice questions",
		"Send questions to other",
	];

	const db = useContext(FirebaseContext);

	return (
		<div>
			<Head>
				<title className="text-blue-200">Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<main className="flex flex-row h-screen mt-12">
				<article className="flex flex-col h-full z-20">
					<section className="pt-4 px-4">
						<h2 className="text-blue-600 font-extrabold tracking-tighter text-7xl">
							Practice Makes Perfect
						</h2>
						<ul className="mt-3 px-3">
							{lists.map((list) => {
								return (
									<li className="flex flex-row items-center my-1 text-lg font-medium">
										<MdOutlineCheckBox className="mr-1" />
										{list}
									</li>
								);
							})}
						</ul>
					</section>
					<div class="custom-shape-divider-top-1652322951 z-10 h-40">
						<svg
							data-name="Layer 1"
							xmlns="http://www.w3.org/2000/svg"
							viewBox="0 0 1200 120"
							preserveAspectRatio="none"
						>
							<path
								d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z"
								class="shape-fill"
							></path>
						</svg>
					</div>
					<section className="bg-gray-200 flex-grow px-28 z-20 grid grid-cols-2 gap-14">
						<div>
							<h3 className="text-blue-600 font-bold text-2xl mb-2">
								New Questions
							</h3>
							<div className="flex flex-col w-full bg-blue-200 p-2 border-dashed border-blue-600 border-2 rounded-lg">
								<Card className="p-4 flex my-1">
									<div className="text-container flex flex-col">
										<h2>Calculus 1</h2>
										<p>
											Lorem ipsum dolor sit amet
											consectetur adipisicing elit.
											Dolorum magnam quidem accusantium
											ducimus fuga ratione pariatur
											dolores laboriosam sapiente sed?
										</p>
									</div>
									<div className="button-container flex flex-row-reverse">
										<Button>Answer</Button>
										<Button
											variant=""
											className="text-blue-700"
										>
											Discuss
										</Button>
									</div>
								</Card>

								<Card className="p-4 flex my-1">
									<div className="text-container flex flex-col">
										<h2>Calculus 1</h2>
										<p>
											Lorem ipsum dolor sit amet
											consectetur adipisicing elit.
											Dolorum magnam quidem accusantium
											ducimus fuga ratione pariatur
											dolores laboriosam sapiente sed?
										</p>
									</div>
									<div className="button-container flex flex-row-reverse">
										<Button>Answer</Button>
										<Button
											variant=""
											className="text-blue-700"
										>
											Discuss
										</Button>
									</div>
								</Card>
							</div>
						</div>
						<div>
							<h3 className="text-blue-600 font-bold text-2xl mb-2">
								Top Questions
							</h3>
							<div className="flex flex-col w-full bg-blue-200 p-2 border-dashed border-blue-600 border-2 rounded-lg">
								<Card className="p-4 flex my-1">
									<div className="text-container flex flex-col">
										<h2>Algebra</h2>
										<p>
											Lorem ipsum dolor sit amet
											consectetur adipisicing elit.
											Dolorum magnam quidem accusantium
											ducimus fuga ratione pariatur
											dolores laboriosam sapiente sed?
										</p>
									</div>
									<div className="button-container flex flex-row-reverse">
										<Button>Answer</Button>
										<Button
											variant=""
											className="text-blue-700"
										>
											Discuss
										</Button>
									</div>
								</Card>

								<Card className="p-4 flex my-1">
									<div className="text-container flex flex-col">
										<h2>Algebra</h2>
										<p>
											Lorem ipsum dolor sit amet
											consectetur adipisicing elit.
											Dolorum magnam quidem accusantium
											ducimus fuga ratione pariatur
											dolores laboriosam sapiente sed?
										</p>
									</div>
									<div className="button-container flex flex-row-reverse">
										<Button>Answer</Button>
										<Button
											variant=""
											className="text-blue-700"
										>
											Discuss
										</Button>
									</div>
								</Card>
							</div>
						</div>
					</section>
				</article>
				{/* <Sidebar />
                <content className="flex-grow">

                </content> */}
			</main>
		</div>
	);
}