import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import Button from "../components/Generic/Button";
import Sidebar from "../components/Generic/Side";
import Card from "../components/Generic/Card";
import { useContext } from "react";
import { FirebaseContext } from "../firebase/FirebaseContext";
import ShapeDivider from "../components/Generic/ShapeDivider";
import Folder from "../components/Landing/Folder";
import Side from "../components/Generic/Side";
import ProblemCard from "../components/Problem/ProblemCard";
import clsx from "clsx";
import ProblemCard2 from "../components/Problem/ProblemCard2";

const Problems = () => {
	const db = useContext(FirebaseContext);

	const newQuestions = [
		{
			id: "014f",
			topic: "Calculus with Differential Equations",
			subtopic: "Exact Equation",
			owner: "jeffery1941",
			statement: "Solve y' = y.",
			accepted: 514,
			attempted: 41946,
			comments: 31,
		},
		{
			id: "02gf",
			topic: "Calculus with Differential Equations",
			subtopic: "Method of Separation Variables",
			owner: "jeffery1941",
			statement: "Solve y' = y.",
			accepted: 794,
			attempted: 4156,
			comments: 2,
		},
	];

	return (
		<>
			<Head>
				<title className="text-blue-200">Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="relative w-full h-screen mt-12 pl-64">
				<Side />
				<div className="relative top-0">
					<div className="p-8">
						<h1 className="h2">Problems</h1>
					</div>
					{newQuestions.map((card, index) => (
						<ProblemCard
							key={card.id}
							{...card}
							className={clsx("p-8 border-t-2 rounded-none", index !== 0 && "border-b-2")}
						/>
					))}
				</div>
			</main>
		</>
	);
};

export default Problems;
