import Head from "next/head";
import { useContext } from "react";
import { useRouter } from "next/router";
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";
import { getDatabase, ref, set, child, get } from "firebase/database";
import { FirebaseContext, getData, getErrorMessage, postData } from "../components/firebase";
import clsx from "clsx";
import FormTemplate from "../components/FormTemplate";
import * as Yup from "yup";

const RegisterSchema = Yup.object().shape({
	email: Yup.string()
		.email("Email is in the wrong format!")
		.required("Email is required!"),
	username: Yup.string()
		.min(4, "Username is too short!")
		.max(20, "Username is too long!")
		.required("Username is required!"),
	password: Yup.string()
		.min(6, "Password is too short!")
		.max(30, "Password is too long!")
		.required("Password is required!"),
});

const Register = () => {
	const auth = getAuth();
	const router = useRouter();
	const { db } = useContext(FirebaseContext);

	async function register(values) {
		return await new Promise((res, rej) => {
			createUserWithEmailAndPassword(
				auth,
				values["email"],
				values["password"]
			)
				.then(async (cred) => {
					await postData(db, `user/${cred.user.uid}`, {
						email: values["email"],
						username: values["username"],
					});
				})
				.then(async () => {
					await signInWithEmailAndPassword(
						auth,
						values["email"],
						values["password"]
					);
				})
				.then(() => {
					router.push("/problems");
					res(null);
				})
				.catch((error) => {
					rej(getErrorMessage(error.code));
				});
		});
	}

	/*	Firebase's default auth system only knows the email and password of user, so
		naturally its validation system doesn't support checking existing username.
		So I made one myself -jose- */
	async function usernameIsUnique(value) {
		return await getData(db, "/user")
			.then((result) => {
				if(!result)
					return true;
				
				let unique = true;
				for (const [id, user] of Object.entries(result)) {
					console.log([id, user]);
					if (user.username === value) {
						unique = false;
						break;
					}
				}
				return unique;
			})
			.catch((e) => {
				console.log(e);
				return false;
			});
	}

	return (
		<>
			<Head>
				<title>Register</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<FormTemplate
				title="Register"
				formik={{
					initialValues: {
						email: "",
						username: "",
						password: "",
					},
					validationSchema: RegisterSchema,
					onSubmitValidation: usernameIsUnique,
					onSubmitValidationError: {
						type: "username",
						message: "Username is already taken!",
					},
					onSubmit: register,
				}}
				fields={[
					{
						title: "Email",
						id: "email",
						type: "email",
					},
					{
						title: "Username",
						id: "username",
						type: "username",
					},
					{
						title: "Password",
						id: "password",
						type: "password",
					},
				]}
				callback={{ success: () => console.log("Success") }}
			/>
		</>
	);
};

export default Register;
